### ISSUE TITLE
2x 350mm Frame

### ISSUE THREAD

**Issue by Fragmon** [Ressetkk/Vyper_SW#1]
Thank you for this repo. Is this a TYPO? You write 2x 350mm and 1x330. I think you mean 1x 350 and 1x 330mm or 2x350 and cut one down?

**Comment by Ressetkk** [comment]
Exactly!
2x 350mm 2020 extrusions and cut one down to 330mm, or 1x 350 mm and 1x 330mm to avoid cutting.

**Comment by Ressetkk** [comment]
Fixed incorrect count of 350mm extrusions.
